import {
  ApplicationConfig,
  ErrorHandler,
  importProvidersFrom,
  provideZoneChangeDetection,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  Flower2,
  Leaf,
  Snowflake,
  Sun,
  ArrowRight,
  ArrowDown,
  BellRing,
  Bell,
  BrainCircuit,
  Bug,
  Building2,
  BookOpen,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  BookOpenCheck,
  ClipboardList,
  Clock,
  ChartColumnIncreasing,
  Code2,
  Cpu,
  Database,
  Eye,
  EyeOff,
  FileDown,
  FileSpreadsheet,
  Globe,
  GraduationCap,
  History,
  Info,
  LayoutDashboard,
  Layers,
  LifeBuoy,
  Lightbulb,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Newspaper,
  Pencil,
  Phone,
  Plus,
  School,
  Search,
  Server,
  Shield,
  Table,
  Target,
  Trash2,
  Triangle,
  User,
  UserCheck,
  UserPlus,
  UserX,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Workflow,
  XCircle,
  Zap,
  CheckCircle,
  Check,
  Users,
  X,
  Send,
  ImagePlus,
  FileText,
  Bot,
  LoaderCircle,
} from 'lucide-angular';

import { routes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import { GlobalErrorHandler } from './shared/components/error-handling/global-error-handler';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    {
      provide: ErrorHandler,
      useClass: GlobalErrorHandler,
    },
    // Bat change detection theo Zone de UI tu dong cap nhat sau callback async.
    provideZoneChangeDetection({ eventCoalescing: false, runCoalescing: false }),
    provideRouter(routes),
    provideAnimationsAsync(),
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertCircle,
        AlertTriangle,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        Bell,
        BellRing,
        BrainCircuit,
        Building2,
        BookOpen,
        Bug,
        ClipboardList,
        Clock,
        Code2,
        Cpu,
        Database,
        BookOpenCheck,
        ChevronDown,
        ChevronRight,
        ChevronUp,
        ChartColumnIncreasing,
        CheckCircle,
        Check,
        Eye,
        EyeOff,
        FileDown,
        FileSpreadsheet,
        Flower2,
        Globe,
        GraduationCap,
        History,
        Info,
        LayoutDashboard,
        Layers,
        Leaf,
        LifeBuoy,
        Lightbulb,
        Loader2,
        Lock,
        LogIn,
        LogOut,
        Mail,
        MapPin,
        Menu,
        MessageCircle,
        MessageSquare,
        Newspaper,
        Pencil,
        Phone,
        Plus,
        School,
        Search,
        Server,
        Snowflake,
        Sun,
        Shield,
        ShieldCheck,
        Sparkles,
        Table,
        Target,
        Send,
        TrendingUp,
        Trash2,
        Triangle,
        User,
        UserCheck,
        UserPlus,
        UserX,
        Users,
        Workflow,
        XCircle,
        X,
        Zap,
        ImagePlus,
        FileText,
        Bot,
        LoaderCircle,
      }),
    ),
    // Cau hinh HttpClient toan cuc va tu dong gan JWT cho moi request.
    provideHttpClient(withInterceptors([jwtInterceptor])),
  ],
};
