import {
  ApplicationConfig,
  ErrorHandler,
  importProvidersFrom,
  provideZoneChangeDetection,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { MatSnackBarModule } from '@angular/material/snack-bar';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  BellRing,
  Bell,
  BrainCircuit,
  Building2,
  BookOpen,
  ChevronRight,
  ChevronDown,
  BookOpenCheck,
  ClipboardList,
  ChartColumnIncreasing,
  Code2,
  Cpu,
  Database,
  Eye,
  EyeOff,
  FileDown,
  FileSpreadsheet,
  GraduationCap,
  Info,
  LayoutDashboard,
  Layers,
  Lightbulb,
  Lock,
  LogIn,
  LogOut,
  LucideAngularModule,
  Mail,
  Menu,
  Newspaper,
  Pencil,
  Plus,
  School,
  Search,
  Server,
  Shield,
  Trash2,
  Triangle,
  User,
  UserCheck,
  UserPlus,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Workflow,
  XCircle,
  Zap,
  CheckCircle,
  Users,
} from 'lucide-angular';

import { routes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import { GlobalErrorHandler } from './shared/components/error-handling/global-error-handler';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    {
      provide: ErrorHandler,
      useClass: GlobalErrorHandler,
    },
    // Bat change detection theo Zone de UI tu dong cap nhat sau callback async.
    provideZoneChangeDetection({ eventCoalescing: false, runCoalescing: false }),
    provideRouter(routes),
    provideAnimationsAsync(),
    importProvidersFrom(
      MatSnackBarModule,
      LucideAngularModule.pick({
        AlertCircle,
        AlertTriangle,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        Bell,
        BellRing,
        BrainCircuit,
        Building2,
        BookOpen,
        ClipboardList,
        Code2,
        Cpu,
        Database,
        BookOpenCheck,
        ChevronDown,
        ChevronRight,
        ChartColumnIncreasing,
        CheckCircle,
        Eye,
        EyeOff,
        FileDown,
        FileSpreadsheet,
        GraduationCap,
        Info,
        LayoutDashboard,
        Layers,
        Lightbulb,
        Lock,
        LogIn,
        LogOut,
        Mail,
        Menu,
        Newspaper,
        Pencil,
        Plus,
        School,
        Search,
        Server,
        Shield,
        ShieldCheck,
        Sparkles,
        TrendingUp,
        Trash2,
        Triangle,
        User,
        UserCheck,
        UserPlus,
        Users,
        Workflow,
        XCircle,
        Zap,
      }),
    ),
    // Cau hinh HttpClient toan cuc va tu dong gan JWT cho moi request.
    provideHttpClient(withInterceptors([jwtInterceptor])),
  ],
};
